name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build without tests
      run: ./gradlew build -x test

    - name: Start local server (background)
      run: |
        java -jar ./artifacts/app-order.jar &
        sleep 10  # ждем , пока сервер поднимется

    - name: Run tests
      run: ./gradlew test

    - name: Upload test report if tests fail
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: build/reports/tests/test
